base_url = "/"
compile_sass = true
build_search_index = false
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[languages.en]
title = "willcool4ever"
description = "Think different. Make a difference!"
generate_feeds = true
taxonomies = [
    {name = "tags"},
]

[languages.zh]
title = "少言才不会咸"
description = "诚者先知"
generate_feeds = true
taxonomies = [
    {name = "tags"},
]

[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[languages.zh.translations]
language_name = "中文"
home = "首页"
about = "关于"
tags = "标签"
archive = "归档"
links = "友链"
date_format = "%Y-%m-%d"
next_page = "下一页"
last_page = "上一页"

[extra.social]
github = "https://github.com/willku1024/"
twitter = ""
facebook = ""
instagram = ""
dribbble = ""
weibo = ""
linkedin = ""
flickr = ""

[extra.show]
tags = true
links = true
