name = "anatole-zola"
description = "A port of farbox-theme-Anatole for zola"
license = "MIT"
homepage = "https://github.com/longfangsong/anatole-zola"
min_version = "0.4.0"
demo = "https://longfangsong.github.io"

[extra]
name = "extra"

[author]
name = "willcool4ever"
homepage = "https://blog.coderr.cn/"

[original]
author = "willcool4ever"
homepage = "https://blog.coderr.cn/"
repo = "https://willku1024.github.com/"
